### ISSUE TITLE
Sessions in SL not properly closed after an error

### ISSUE THREAD

**Issue by wswebcreation** [saucelabs/speedo#49]
When using Speedo I sometimes get an error `unknown error` like in the logs below. When I look at the SL dashboard the instances are still running and I or need to stop them manually or need to wait till they time-out.
Can this be handled by Speedo?

```log
➜ ✗ speedo run http://www.wswebcreation.nl
✔ Start performance test run with user wim.selles on page http://www.wswebcreation.nl...
⠼ Couldn't find baseline for job with name Performance test for http://www.wswebcreation.nl, creating baseline...speedo run [params...] <site>

Run performance tests on any website.

Options:
  --version               Show version number                          [boolean]
  --help, -h              prints speedo help menu                      [boolean]
  --user, -u              your Sauce Labs username
  --key, -k               your Sauce Labs user key
  --region, -r            your Sauce Labs datacenter region, the following
                          regions are available: `us-west-1` (short `us`),
                          `eu-central-1` (short `eu`)            [default: "us"]
  --logDir, -l            directory to store logs from testrun
  --traceLogs, -t         if set runner downloads tracing logs for further
                          investigations
  --platformName, -p      the platform the performance test should run in (e.g.
                          "Windows 10")                  [default: "Windows 10"]
  --browserVersion, -v    the browser version of Chrome the performance test
                          should run in (e.g. "latest")      [default: "latest"]
  --build, -b             name of the build you want to run your performance
                          test in
  --name, -n              name of your performance test
  --metric, -m            metric that you want to check (multiple possible)
                                                               [default: "load"]
  --all                   check on all metrics        [boolean] [default: false]
  --throttleNetwork       throttle network speed for your test (e.g. "Good 3G")
                                                            [default: "Good 3G"]
  --throttleCpu           throttle cpu speed for your test (e.g. "4" for 1/4
                          speed)                                    [default: 4]
  --retry                 amount of retries for failing performance tests
                                                           [number] [default: 0]
  --tunnelIdentifier, -i  identifier for Sauce Connect tunnel to run performance
                          tests for local hosted apps
  --parentTunnel          username of parent running Sauce Connect tunnel

{ unknown error: Something went wrong with recording the trace over your page load. Please run the command again.
    at getErrorFromResponseBody (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/webdriver/build/utils.js:349:10)
    at Request._callback (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/Users/wimselles/.nvm/versions/node/v10.15.2/lib/node_modules/speedo/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13) name: 'unknown error' }
```

**Comment by christian-bromann** [comment]
fixed in #52
