### ISSUE TITLE
Running the latest speedo on node.js v10 throws an error

### ISSUE THREAD

**Issue by adambabik** [saucelabs/speedo#77]
Steps to reproduce:
```
$ node -v
v10.12.0

$ npm install speedo@latest

$ ./node_modules/.bin/speedo -h
/private/tmp/wdio/node_modules/speedo/build/utils.js:29
const ctx = new _chalk.default.constructor({
            ^

TypeError: _chalk.default.constructor is not a constructor
    at Object.<anonymous> (/private/tmp/wdio/node_modules/speedo/build/utils.js:29:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/private/tmp/wdio/node_modules/speedo/build/commands/analyze.js:14:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
```

**Comment by christian-bromann** [comment]
Fixed by https://github.com/saucelabs/speedo/pull/78
